### ISSUE TITLE
Problem with dragging when chart is not in fullscreen

### ISSUE THREAD

**Issue by pixelshocks** [chrispahm/chartjs-plugin-dragData#1]
Hello,

Firstly thanks for the awesome plugin! 

I have a chart that doesn't fill the screen, when I do a drag interaction (y-axis only), the position goes haywire, I did a quick fix by adding an offset to the value in the updateData function:

```javascript
function updateData(chartInstance, callback) {
	return function () {
		if (element && _d3Selection.event) {
			var e = _d3Selection.event.sourceEvent;
			var datasetIndex = element['_datasetIndex'];
			var index = element['_index'];
			var value = chartInstance.scales[scale].getValueForPixel(e.clientY-chartInstance.canvas.getBoundingClientRect().y);
			chartInstance.data.datasets[datasetIndex].data[index] = value;
			chartInstance.update(0);
			if (typeof callback === 'function') callback(e, datasetIndex, index, value);
		}
	};
}
```

**Comment by chrispahm** [comment]
Nice, thanks for the heads up! 
I tried adding your suggestion (substracting the value of `chartInstance.canvas.getBoundingClientRect().y` from the Y-Pixel value) to the code, however it basically left me with a deletion of the data point. Could you set up an example (jsFiddle or else) of how this setup worked for you?
Also, the browser you used for testing may be of interest.

**Comment by chrispahm** [comment]
Ok, I guess you meant `chartInstance.canvas.getBoundingClientRect().top` there! I updated the code and added an [example for a small chart](https://chrispahm.github.io/chartjs-plugin-dragData/smallChart.html). Also you may want to fix the y-scales on such small charts for a better user experience. Again, thanks a lot for posting the issue!
