### ISSUE TITLE
ERROR: Cannot assign to read only property 'x' of object '#<Object>'. Fix inside.

### ISSUE THREAD

**Issue by bpGusar** [chrispahm/chartjs-plugin-dragData#13]
At first dragging of any point all ok, X coordinate saved, but at second drag i getting error:
```
Uncaught TypeError: Cannot assign to read only property 'x' of object '#<Object>'
    at HTMLCanvasElement.<anonymous> (chartjs-plugin-dragData.js:177)
    at Dispatch.apply (chartjs-plugin-dragData.js:1611)
    at Object.customEvent (chartjs-plugin-dragData.js:1315)
    at Object.gesture [as mouse] (chartjs-plugin-dragData.js:450)
    at mousemoved (chartjs-plugin-dragData.js:362)
    at chartjs-plugin-dragData.js:1218
```

In file chartjs-plugin-dragData.js lines from 124 to 132 i change to this and all works normally
```
if (chartInstance.data.datasets[datasetIndex].data[index].x !== undefined && chartInstance.options.dragX) {
	chartInstance.data.datasets[datasetIndex].data[index] = {
		...chartInstance.data.datasets[datasetIndex].data[index],
		x: x, 
	}
}

if (chartInstance.data.datasets[datasetIndex].data[index].y !== undefined) {
	chartInstance.data.datasets[datasetIndex].data[index] = {
		...chartInstance.data.datasets[datasetIndex].data[index],
		y: y, 
	}
} else {
	chartInstance.data.datasets[datasetIndex].data[index] = {
		...chartInstance.data.datasets[datasetIndex].data[index],
		y: y, 
	}
}
```

Maybe this solution not correct but its working.

**Comment by chrispahm** [comment]
Hey @bpGusar,

sorry for taking me so long. I'm actually having trouble to reproduce your issue. The part of the code you referenced (copied from the current `master`):
```js
      if(chartInstance.data.datasets[datasetIndex].data[index].x !== undefined && chartInstance.options.dragX) {
        chartInstance.data.datasets[datasetIndex].data[index].x = x
      }

      if(chartInstance.data.datasets[datasetIndex].data[index].y !== undefined) {
        chartInstance.data.datasets[datasetIndex].data[index].y = y
      }
      else {
        chartInstance.data.datasets[datasetIndex].data[index] = y
      }
```
makes sure that the preceding value of the data point that was clicked upon is replaced by the new value according to the mouse/finger position. Then, the `update` method is called for the changes to take effect. So far so good!

Now the error you are receiving  
```
Uncaught TypeError: Cannot assign to read only property 'x'
```
makes we wonder if your `chartInstance`(and all it's properties) object was turned reactive by a framework like `react` / `vue`. In that case, we cannot directly assign values to the properties of a `chartInstance`, but rather have to use a `setter`. I'm a `Vue` use myself (and currently have next to no knowledge about `react`), and reading the ["Reactivity in Depth"](https://vuejs.org/v2/guide/reactivity.html) section of the documentation helped me a lot.

If this actually describes your case, one would have to think about the best way to achieve the desired behaviour. Does the `chartInstance` really have to be reactive in the first place? If you could provide some more info and ideally an example in `jsFiddle/codePen` etc. that would be really helpful.
Thanks for your patience!

Btw.: I also went through your PR, see the comments made there.

**Comment by chrispahm** [comment]
Closing this for now, let me know when the problem persists and a reproducible example is available.
