### ISSUE TITLE
Announcing new maintainer: @artus9033

### ISSUE THREAD

**Issue by chrispahm** [chrispahm/chartjs-plugin-dragdata#130]
Hey everyone 👋 

as you may have noticed, development in this repo slowed down in the past year. Since I don't work with Chart.js anymore, it's difficult to find the time required to work on issues and PRs. Also, since [tests have been missing](#40) from the start, evaluating PRs currently takes much longer than necessary, and chances are high that a fix for one bug causes a few other bugs somewhere else.

Therefore, I am very happy to announce that **@artus9033** has agreed to take over as the new maintainer of chartjs-plugin-dragdata. He is a talented developer, already [proposed a clean TypeScript re-write](#86), and I have full confidence in his abilities and vision. He will be responsible for reviewing pull requests, merging code, releasing new versions, and managing the issues. This repo will be transferred to his account in the coming days.

I want to thank you all for your support and feedback over the years, and I hope you will continue to use and contribute to this project.

Please join me in welcoming **artus9033** as the new maintainer and wishing him all the best for the future of chartjs-plugin-dragdata 🎉 

Cheers,
Christoph

**Comment by artus9033** [comment]
Thank you for the introduction and kind words @chrispahm! I will make sure that the development of the plugin is continued and am sure that together with the community we will continuously be improving it even further  🔧

**Comment by karloluis** [comment]
Have been doing some research for Radar Charts the past few days for a new project I'm starting. Short of it is that I was starting to dread the idea of creating my own event listeners and scouring through Canvas docs until I found https://github.com/chartjs/Chart.js/issues/5931 that addresses my needs.

Makes me happy to see that the plugin is still alive and will likely be using it very soon. Thanks for saving me a good few days of work!
