### ISSUE TITLE
X-axis Drag like on picture

### ISSUE THREAD

**Issue by Extnow** [chrispahm/chartjs-plugin-dragData#15]
Hello, thanks for the great plugin.

I have a task to move a line of two points horizontally, could you explain to me this can be done with your plugin?

If so, how to do it in a nutshell? If not, could you advise the tools for this? Thanks

![1](https://user-images.githubusercontent.com/25666714/50207878-d8d44d00-0380-11e9-8710-eeea08511731.png)

**Comment by chrispahm** [comment]
Hey there!
What you want to achieve looks perfectly doable in my opinion (if I understand it right), however, not with this plugin ;)
I think your best bet is the amazing [`chartjs-draggable`-plugin](https://github.com/compwright/chartjs-plugin-draggable). Here is a [CodePen](https://codepen.io/OutOfNutella/pen/RgJEKY/) doing almost exactly what you want to achieve, but with a horizontal bar. In the repo I saw that there may be some issues with the vertical bars, but I guess you would have to check it out and try!
