### ISSUE TITLE
trigger an event onDragEnd

### ISSUE THREAD

**Issue by krishaws** [chrispahm/chartjs-plugin-dragData#17]
I am trying to call a function onDragEnd. I want to pass the values as an arguments where the script displays the updated values in the console. 

`
onDragEnd: function (e, datasetIndex, index, value) {

					console.log(datasetIndex, index, value)
					
					this.modifyDataSet(datasetIndex, index, value);
				}`

Console.log works fine. But I dont know how to trigger a custom function. I need to project the values in a datagrid in parallel to the chart. Your help would be highly appreciated. Thanks

**Comment by krishaws** [comment]
You are really amazing. Thanks a lot for your quick reply. I didn't read
your email yet. I'll check and get back to you.

I just want to say thanks for your contribution and I simply admires you.

I'm using Angular and I'm new to this language.

Regards,
Krish.

**Comment by chrispahm** [comment]
Sure thing, glad to help you out :)
I'll close this for now, let me know if you run into any trouble

**Comment by krishaws** [comment]
Hi Christoph,

Please have a look at the below code. I tried placing the method outside as
you mentioned. But still there is an exception. Your help is much
appreciated. Thanks.

I use Angular. I am implementing chart.js with your plugin. My colleagues
were suggesting to go for DevExpress. But I want to prove them that we can
achieve the dragging functionality even with your plugin. It would be great
if you can provide me your email address. Thanks.

Regards,
Krish



import { Component, OnInit } from '@angular/core';
import { Chart } from 'chart.js';
import '../../assets/js/chartjs-plugin-dragData.js';
import { ChartDataService } from '../chart-data.service';
import { DataService } from "../data.service";
import { promise } from 'protractor';


@Component({
    selector: 'app-line-chart',
    templateUrl: './line-chart.component.html',
    styleUrls: ['./line-chart.component.css']
})
export class LineChartComponent implements OnInit {
    message: string;
    chart: any[];

    constructor(private dataService: ChartDataService, private dataSer:
DataService) {

    }


    async ParseChartValues(response) {


        var chart = [];
        // Preparing the dataset for the Chart
        let finaldata = {
            datasets: []
        }

        for (let i = 0; i < response.length; i++) {

            let newDataset = {
                label: response[i].label,
                borderColor: response[i].borderColor,
                fill: true,
                data: response[i].data.split(',')
            }

            finaldata.datasets.push(newDataset);

        }



        chart = new Chart('canvas', {
            type: 'line',
            data: {
                labels: ['January', 'February', 'March', 'April', 'May',
'June', 'July', 'August', 'September', 'October', 'November', 'December'],
                datasets: finaldata.datasets
            },
            options: {
                responsive: true,
                title: {
                    display: false,
                    text: 'Line Chart'
                },
                tooltips: {
                    mode: 'index',
                    intersect: false,
                },
                hover: {
                    mode: 'nearest',
                    intersect: true
                },
                scales: {
                    xAxes: [{
                        display: true,
                        scaleLabel: {
                            display: true,
                            labelString: 'Month'
                        }
                    }],
                    yAxes: [{
                        display: true,
                        scaleLabel: {
                            display: true,
                            labelString: 'Volume'
                        }
                    }]
                },
                dragData: true,
                onDragStart: this.modifyDataSet,
                onDrag: function (e, datasetIndex, index, value) {
                    //console.log(datasetIndex, index, value)
                },
                onDragEnd: function (e, datasetIndex, index, value) {

                    console.log(datasetIndex, index, value)

                }
            }

        });


    }


    ngOnInit() {
        this.invokeAPICall();
    }

    async invokeAPICall() {
        await this.dataService.getChartValues(this.ParseChartValues);

        return '';
    }

    modifyDataSet() {
        console.clear();
        console.log('modify data set');
        console.log(this.dataSer.currentData);
    }

    updateGraph() {

        console.log('button clicked');

    }
}

**Comment by chrispahm** [comment]
Hey Krish,

sorry for my lack of knowledge in Angular and Typescript, but I *hope* the following code should get the job done:

```js
import { Component, OnInit } from '@angular/core';
import { Chart } from 'chart.js';
import '../../assets/js/chartjs-plugin-dragData.js';
import { ChartDataService } from '../chart-data.service';
import { DataService } from "../data.service";
import { promise } from 'protractor';

@component({
  selector: 'app-line-chart',
  templateUrl: './line-chart.component.html',
  styleUrls: ['./line-chart.component.css']
})

export class LineChartComponent implements OnInit {
  message: string;
  chart: any[];

  constructor(private dataService: ChartDataService, private dataSer:
    DataService) {

  }

  async ParseChartValues(response) {
    var chart = [];
    // Preparing the dataset for the Chart
    let finaldata = {
      datasets: []
    }

    for (let i = 0; i & lt; response.length; i++) {
      let newDataset = {
        label: response[i].label,
        borderColor: response[i].borderColor,
        fill: true,
        data: response[i].data.split(',')
      }
      finaldata.datasets.push(newDataset);
    }

    // specify default chart options
    const chartOptions = {
      type: 'line',
      data: {
        labels: ['January', 'February', 'March', 'April', 'May',
          'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        datasets: finaldata.datasets
      },
      options: {
        responsive: true,
        title: {
          display: false,
          text: 'Line Chart'
        },
        tooltips: {
          mode: 'index',
          intersect: false,
        },
        hover: {
          mode: 'nearest',
          intersect: true
        },
        scales: {
          xAxes: [{
            display: true,
            scaleLabel: {
              display: true,
              labelString: 'Month'
            }
          }],
          yAxes: [{
            display: true,
            scaleLabel: {
              display: true,
              labelString: 'Volume'
            }
          }]
        },
        dragData: true
      }
    }

    // specify onDragEnd callback function
    chartOptions.options.onDragEnd = this.modifyDataSet

    // initiate chart
    chart = new Chart('canvas', chartOptions);

  }

  ngOnInit() {
    this.invokeAPICall();
  }

  async invokeAPICall() {
    await this.dataService.getChartValues(this.ParseChartValues);

    return '';
  }

  modifyDataSet(e, datasetIndex, index, value) {
    console.clear();
    console.log('modify data set');
    console.log(e, datasetIndex, index, value)
    console.log(this.dataSer.currentData);
  }

  updateGraph() {
    console.log('button clicked');
  }

}
```
If it still does not work, can you tell me what exception you are receiving?
Best
Christoph

**Comment by krishaws** [comment]
Hi Christoph,

I tried your way. But the problem still persists. this keyword doesn't
recognize the method exists. Please see the attached screenshot. Thanks. It
would be great if you can provide me a solution.

Best Regards,
Krish

[image: image.png]

        const chartOptions =
         {
            type: 'line',
            data: {
                labels: ['January', 'February', 'March', 'April', 'May',
'June', 'July', 'August', 'September', 'October', 'November', 'December'],
                datasets: finaldata.datasets
            },
            options: {
                responsive: true,
                title: {
                    display: false,
                    text: 'Line Chart'
                },
                tooltips: {
                    mode: 'index',
                    intersect: false,
                },
                hover: {
                    mode: 'nearest',
                    intersect: true
                },
                scales: {
                    xAxes: [{
                        display: true,
                        scaleLabel: {
                            display: true,
                            labelString: 'Month'
                        }
                    }],
                    yAxes: [{
                        display: true,
                        scaleLabel: {
                            display: true,
                            labelString: 'Volume'
                        }
                    }]
                },
                dragData: true
            }


        };

        chartOptions.options.onDragEnd = this.modifyDataSet;

        chart = new Chart('canvas', chartOptions);

**Comment by chrispahm** [comment]
Hey Krish,
unfortunately I didn't receive your image, it looks like you send it via E-Mail. Can you attach it again in this thread which you can find under [https://github.com/chrispahm/chartjs-plugin-dragData/issues/17](https://github.com/chrispahm/chartjs-plugin-dragData/issues/17)

**Comment by krishaws** [comment]
![browser-error](https://user-images.githubusercontent.com/47323963/52330201-1c4c4e80-29f5-11e9-9865-72c8bda0798b.JPG)

**Comment by krishaws** [comment]
I fixed this issue by placing all the chart generation code inside the subscribe function of HTTPGetRequest. Now the onDrag events can trigger my outside functions. However, I found an issue. 
onDrag events trigger just only the first event right after `dragData: true,`. In this example, `this.modifyDataSet` gets triggered only on onDragEnd. onDrag and onDragStart shows the method is undefined. I dont know what causes this issue. But for the time being its helpful that I need my function to be triggered only onDragEnd. Does any experience this issue?

`
onDragEnd: (e, datasetIndex, index, value) => {
						this.modifyDataSet(datasetIndex, index, value)
					},
					onDrag: function (e, datasetIndex, index, value) {
						this.modifyDataSet(datasetIndex, index, value)
					},
					onDragStart: function (e, datasetIndex, index, value) {
						this.modifyDataSet(datasetIndex, index, value)
					}
`

**Comment by chrispahm** [comment]
Hey there,

glad you could resolve your issue! As expected the error stems from the way your functions are set up. 
It look like for the `onDragEnd` function you use an ES6 arrow function, whereas for the others you don't. Keep in mind that by not using arrow functions in JavaScript, the value of `this` can often be misleading.

```js
onDragEnd: (e, datasetIndex, index, value) => { this.modifyDataSet(datasetIndex, index, value) },
onDrag: (e, datasetIndex, index, value) => { this.modifyDataSet(datasetIndex, index, value) }, 
onDragStart: (e, datasetIndex, index, value) => { this.modifyDataSet(datasetIndex, index, value) }
```
That should to the trick. 
If you got some time on your hands, I really recommend [this course](https://github.com/domenic/count-to-6) on all ES6 features that were implemented in JS, it really helped me understanding some of these concepts!

**Comment by krishaws** [comment]
Thanks Christoph. That works. My bad. :)
