### ISSUE TITLE
Stacked Bar Chart

### ISSUE THREAD

**Issue by krishRamalingam** [chrispahm/chartjs-plugin-dragdata#19]
The plugin works fine for the bar chart. But I tried it with the stacked bar. it works fine for the bottom bar. But when I try to drag the top bar the top point jumps suddenly to a different point. 

I believe  you can support the stack bar with some minimal changes as its almost working. Thanks.

**Comment by chrispahm** [comment]
Hey @krishaws,
thanks for pointing this out. Unfortunatetly, I have almost no time for any enhancements to this project at the moment. Maybe you can ask a colleague or friend to have a look at the code, and do a Pull Request afterwards. Or maybe someone from the community can help us out here?
Best
Christoph

**Comment by krishaws** [comment]
No Problem Christoph. I try my level best.

Krish

**Comment by chrispahm** [comment]
Ok so I was working getting bar charts to work (together with some other stuff), and I think the stacked bar charts should now be working in the most recent version. Could you have a look and 
Here's an example:
confirm? https://chrispahm.github.io/chartjs-plugin-dragData/stackedBar.html

**Comment by chrispahm** [comment]
Closing this as answered for now, please re-open if the issue persists.
