### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by vsoch** [chrispahm/chartjs-plugin-dragdata#23]
I was looking for this exact functionality, and I found your repository, added the tag, and boum! It just worked! Thank you so much, so wonderful when the stars align! <3

**Comment by chrispahm** [comment]
Hey @vsoch! Thanks so much for the :heart:, really means a lot to me :) It’s wonderful coming to work and having this in your inbox :)

**Comment by vsoch** [comment]
Awesome!

If you are interested in what I'm working on (and it still needs a lot of work because I started yesterday evening) it's an "RSE Phenotype generator" -> https://us-rse.org/rse-phenotype/

I need to give it more context and a few more controls, but try dragging the points on the plot!

**Comment by chrispahm** [comment]
Looks very cool, I just read through the about page to get the bigger picture :) so is the idea to better reflect on own abilities as an RSE? Or is it meant to help communicate own interests and strengths? I guess I should create myself a Twitter account and Post a Plot myself ;)

**Comment by vsoch** [comment]
You definitely should! A few folks (some of the higher ups) in the usrse community (which is rather new) are boldly writing papers, blog posts, that explicitly say "This is what it means to be an RSE." While some of the points are on target (e.g., doing software engineering and research) it didn't seem right to be to define such limited buckets and then stake claim that everyone who identifies as RSE must fit in them. My view is that there are more dimensions, and then different communities that could be defined under each (e.g., I might do a lot of software testing for open source, but not as much for academia, or something like that) so instead of trying to define what it means to be an RSE a priori, why not just ask people directly? People who self identify as RSEs are really the best ones to say what it means to them. And this is important for the general community to know, because we need to best support people and meet their goals. I wrote a little more on it here if you are interested! https://vsoch.github.io/2019/what-is-an-rse/

**Comment by chrispahm** [comment]
Yeah that totally makes sense! 
It's funny that you bring this up, I never really though about calling myself a RSE... But in fact, this library was build for a research effort: 
For a (still to be written) paper about single farm optimization, I need farmers to report on their own yields and prices, as well as work load for the crops they grow. I didn't want them to fill out tables, as many of them only have guesstimates about these figures from the past, and also often use a lot of heuristics to make decisions. So I wanted a way to fill in the timeline that felt more fun and would visualize the data at the same time (plus a lot of these guys use iPads more comfortably than PCs, where dragging feels more natural than on a PC). That's where the idea for the draggable charts came from...
![fruchtfolge_drag](https://user-images.githubusercontent.com/20703207/61458811-ab2da180-a96b-11e9-90ae-7fc3dbec444e.gif)

**Comment by vsoch** [comment]
Wow that's beautiful! You should definitely share your work, more informally (e.g.. a blog or similar) because there are a ton of use cases for a tool like this. There isn't much establishment of RSE as an actual career track in most universities in the US, so my hope is that writing, sharing experiences, small things like that can help with awareness, and awareness will carry forward to real world important things like a university funding official RSE positions full time (vs. the current living on fumes from grants, haha).

**Comment by vsoch** [comment]
hey @chrispahm - apologies that I forgot to close this issue! But I'm glad that there was the little delay, because some time has gone by and I've since started a podcast called [RSE Stories](https://us-rse.org/rse-stories/). This is just a random inquiry, but it seems like you have a fairly unique perspective in the kind of work that you do (beautiful visualizations paired with science!)

Would you be interested (sometime in the new year) in being a guest on the Podcast? Given the time difference, we'd probably do an early time where I am, and late afternoon for you. It's fairly low key, and just means joining a zoom session and answering questions / talking about yourself. Let me know if you might be interested - I'd love to talk to you and showcase your work.

**Comment by chrispahm** [comment]
Hey @vsoch! 
No worries, I just went through the issues and thought I'd close some of the older ones 😄 
I kept thinking about your suggestion of writing a blog, but besides creating a template I never got started...
Really cool to hear about your podcast, and thanks so much for asking me about being a guest 😊I feel really honored, and would love to be on the podcast!  We can probably talk about it easier via e-mail, so here it goes: christoph.pahmeyer@ilr.uni-bonn.de
Thanks again, and wish you all the best with your projects 🎉
