### ISSUE TITLE
in package.json main attribute is looking for non existent javascript file

### ISSUE THREAD

**Issue by gspeach** [chrispahm/chartjs-plugin-dragData#26]
Hello,

I was having a heck of a time getting this thing to import, and I noticed in the package.json the main attribute is "main": "dist/chartjs-plugin-dragData.js". However, in the dist folder, there is only a .min.js file. So it's looking for a file that doesn't exist.

Thanks

**Comment by chrispahm** [comment]
Oh I'm sorry! I updated the webpack dependency in a past commit and forgot to include the build for the main file. Sorry about that, should be fixed by version `0.4.2`. Would be nice if you could confirm.

**Comment by gspeach** [comment]
Looks good to me!

Thanks
