### ISSUE TITLE
Issue with bubble chart 

### ISSUE THREAD

**Issue by MrDarrenMcGrath** [chrispahm/chartjs-plugin-dragdata#29]
Hello thanks for the plugin!
There is an issue with dragging the bubble chart items in https://cdn.jsdelivr.net/npm/chartjs-plugin-dragdata@1.0.0/dist/chartjs-plugin-dragdata.min.js

however it works in https://cdn.jsdelivr.net/npm/chartjs-plugin-dragdata@0.3.1/dist/chartjs-plugin-dragData.j

Thanks again

**Comment by chrispahm** [comment]
Hey there,
sorry about that, should be fixed in `v1.0.1`
Best
Christoph

**Comment by chrispahm** [comment]
Closing this as fixed, please re-open if the issue persists.
