### ISSUE TITLE
Floating point number with stacked bars

### ISSUE THREAD

**Issue by josh-s-g** [chrispahm/chartjs-plugin-dragdata#31]
Firstly, what a great library, thanks! 
I'm having some trouble with a stacked bar chart with all-but-one of the series having value 0 (this is so I can have multiple data labels to draw the ˅˄). I've set 
```
dragData: false
```
for the series with value 0, but sometimes when dragging the remaining visible bar section, I get a lot of decimal places in the value:
![lots_of_decimals](https://user-images.githubusercontent.com/9271916/63573978-9fdb2080-c57e-11e9-8991-991cb5e5da84.gif)

I have set 
```
dragDataRound: 1,
```
Am I doing something wrong here? Or is it a likely to be an interaction with the multiple datasets and labels?

**Comment by chrispahm** [comment]
Hey there! 
That chart looks beautiful with these little arrows! Very nice way of suggesting that the chart can be interacted with :)
This look like a bug to me... However, without your particular setup I cannot reproduce it. Would you be willing to share a jsFiddle/Plunker/HTML file so I can have a look?

Best
Christoph

**Comment by josh-s-g** [comment]
Thank you! I'll see if I can find 5 mins to stick it in a jsFiddle, but in the meantime could it be something to do with https://github.com/chrispahm/chartjs-plugin-dragdata/blob/master/src/index.js#L126 ? 

`calcPosition` does some rounding, but looks like `cursorPos - initValue` isn't rounded (based on a 2-minute check, so I might be wrong!).

Thanks

**Comment by chrispahm** [comment]
Well yes, that may be true!
I just made a new branch called [`rounding`](https://github.com/chrispahm/chartjs-plugin-dragdata/tree/rounding), where the line that you are referencing is rounded as well.
You can test the branch by using this file:
[https://chrispahm.github.io/chartjs-plugin-dragdata/assets/chartjs-plugin-dragdata.min.js](https://chrispahm.github.io/chartjs-plugin-dragdata/assets/chartjs-plugin-dragdata.min.js)

**Comment by josh-s-g** [comment]
Yes, that looks to have fixed it! Thanks :+1:
