### ISSUE TITLE
Request / Drag nearest point

### ISSUE THREAD

**Issue by Shakarhaba** [chrispahm/chartjs-plugin-dragdata#32]
As you might know, we can set the mode 'nearest' to trigger the hover action of the points and the tooltips.

```
options = {
    hover: {
        mode: 'nearest',
        intersect: false
    },
    tooltips: {
        mode: 'nearest',
        intersect: false
    }
};
```
It would be perfect that the drag action would work once the point is activated with the 'nearest' mode instead of actually needing to hover over the point.

Thank you

**Comment by chrispahm** [comment]
Hey three,
I think that would be awesome! However, I didn't have the time to think about what would be the best way to achieve this. If you got an idea it would be highly appreciated.
Best
Christoph

**Comment by velthune** [comment]
Hi @Shakarhaba, I've forked the project and added the feature, if you want to try check [it](https://github.com/velthune/chartjs-plugin-dragdata/tree/feature/drag-nearest-point) out!

**Comment by chrispahm** [comment]
Thanks a lot @velthune for the great implementation ❤️ I hope this is what @Shakarhaba was looking for, in any way it's a great addition. Will close this for now, please re-open if this doesn't answer the issue.
