### ISSUE TITLE
Data disappear when it come to x Axis 

### ISSUE THREAD

**Issue by almersawi** [chrispahm/chartjs-plugin-dragdata#33]
If we put a point such as `point = {x: 100, y: 0}` (on x axis), if you click it, it disappear immediately

**Comment by wladimiiir** [comment]
I have found the issue and made a fix. @chrispahm Feel free to review and merge. Thank you.
https://github.com/chrispahm/chartjs-plugin-dragdata/pull/35

**Comment by chrispahm** [comment]
Thanks @wladimiiir for the PR! I'm sorry that I'm currently tight for time, I will try to review it by the end of this week :)

**Comment by chrispahm** [comment]
Ok just published the fix, thanks again @wladimiiir !
