### ISSUE TITLE
d3-drag causing dragData to break in Android Chrome

### ISSUE THREAD

**Issue by gspeach** [chrispahm/chartjs-plugin-dragdata#34]
So after some extensive testing I found that d3-drag is using preventDefault() without passive: true causes dragData to break chart.js chart. Ill try my best to explain, and hope we can find a solution.

**Error Message**

![image](https://user-images.githubusercontent.com/7491714/63720630-9e7b5380-c81d-11e9-93fc-1b772dcf60e5.png)

**Here where it calls .on 'eventType' it should be able to pass a third option passive: true**

`const ChartJSdragDataPlugin = {
  id: 'dragdata',
  afterInit: function(chartInstance) {
    if (chartInstance.options.dragData) {
      select(chartInstance.chart.canvas).call(
        drag().container(chartInstance.chart.canvas)
          .on('start', getElement(chartInstance, chartInstance.options.onDragStart))
          .on('drag', updateData(chartInstance, chartInstance.options.onDrag))
          .on('end', dragEndCallback(chartInstance,chartInstance.options.onDragEnd))
      )
    }
  }
}`

**This is the offending code in d3-drag in noevent.js. Where it calls event.preventDefault();**

`import {event} from "d3-selection";
export function nopropagation() {
  event.stopImmediatePropagation();
}
export default function() {
  event.preventDefault();
  event.stopImmediatePropagation();
}`

**Here are some threads I found in github that might have solutions, but I havent been able to get anything to work.**

[https://github.com/d3/d3-selection/issues/113](https://github.com/d3/d3-selection/issues/113)
[https://github.com/d3/d3-drag/issues/35](https://github.com/d3/d3-drag/issues/35)

**Comment by chrispahm** [comment]
Thanks @gspeach for already inspecting this! Did you get to check if the `drag.touchable` event works for desktop browsers as well? I will try and check your solution by the end of the week!

Best
Christoph

**Comment by chrispahm** [comment]
Just updated to d3-drag v2, which seems to alleviate this issue. Please re-open if it still persists!
