### ISSUE TITLE
the line disappears when dragging dots using touch (small devices)

### ISSUE THREAD

**Issue by msmaricarmanabat** [chrispahm/chartjs-plugin-dragData#4]
![image](https://user-images.githubusercontent.com/18474579/37447504-5ab8b52c-285d-11e8-9360-e56623af92c4.png)

**Comment by chrispahm** [comment]
Sorry, I'm really busy right now. If you got some time on your hands, here is a [Stackoverflow post](https://stackoverflow.com/a/48368153/6213343) describing on how Touchscreen support can be implemented. I would appreciate if you did a PR then, if not I'll get back to this once there is some free time

**Comment by alanbithell** [comment]
Added a PR to fix this

**Comment by chrispahm** [comment]
Thanks @alanbithell for the PR! Just merged it into master
