### ISSUE TITLE
[Question] Possibility to drag a set of points

### ISSUE THREAD

**Issue by yoelz55** [chrispahm/chartjs-plugin-dragdata#46]
Hi, first of all, thank you for this amazing plugin.

I have a simple question, it is possible when dragging a point to drag a set of points?

Example: if I have 100 points in the graph and by dragging one I want to drag the 5 points that surrounds the selected points.

Thanks in advance,

**Comment by chrispahm** [comment]
Hey @yoelz55,

thanks for the ❤️ 

So regarding your question: it is indeed possible to drag multiple points at once. That's one of the main reasons for using the `onDragStart` and `onDrag` callbacks.
I made you a small (and somewhat ugly) fiddle, but I think it illustrates how you can achieve this:
https://jsfiddle.net/45nurh9L/3/

A similar question has been asked in the past, you might also find it helpful to look at the solution posted there:
https://github.com/chrispahm/chartjs-plugin-dragdata/issues/22

Hope this helps
Christoph

**Comment by yoelz55** [comment]
Thank you for your response and your fiddle 💯 

I got it 👍
