### ISSUE TITLE
Not working dragData with angular 5/ typescripr

### ISSUE THREAD

**Issue by toski112** [chrispahm/chartjs-plugin-dragData#5]
I try to use plugin with typescript/angular 5
and its not working,. Im using dragData: true in options my code:
`      options: {
        defaultColor: "#3cba9f",

        legend: { display: true },
        title: {
          display: true,
          text: 'Predicted world population (millions) in 2050'
        },
        scales: {
          margins: {
            right: 10,
            top: 10
          },
          yAxes: [{
            display: true,
            ticks: {
              min: 0,
              max: 16,
              stepSize: 1,
            }
          }],
          xAxes: [{
            ticks: {
              maxRotation: 80,
              minRotation: 75,

            },/*
            type: 'time',

            time: {

              unit: 'minute',
              unitStepSize: 15,
              displayFormats: {
                'minute': 'HH:mm',
                'hour': 'HH:mm'
              },
              min: 1502488800000,
              max: 1502575200000
            }*/
          }]
        },
        dragData: true,
        responsive: false,
      },`

**Comment by chrispahm** [comment]
Hey there, could you provide a minimum working example in JSfiddle/Plunker/...?
I'm neither an Angular nor Typescript user so I'm having trouble to debug this

**Comment by chrispahm** [comment]
Closing this for now. If you stumble upon this issue, please make sure to read the **Gotchas** section of the README first.
