### ISSUE TITLE
request for 1.1.3 release

### ISSUE THREAD

**Issue by mortac8** [chrispahm/chartjs-plugin-dragdata#57]
We use Chart.js and your awesome dragdata plugin for one of our projects.  Issue #56 and chartjs-plugin-dragdata 1.1.3 was a big fix that we needed.

We can't officially use any FOSS code that isn't versioned as a release.  Is there some way I can help create a release for 1.1.3 just like you did for 1.0.2?

**Comment by chrispahm** [comment]
Hey there!
Thanks for the ❤️! Always glad to hear the plugin is being used 😊 
Sorry, I got carried away after closing #56, could have made a release straight away...
I don't follow any actual policy when drafting releases, so I will just make one right away. Is that ok for you or do you need anything to be considered there in particular?

**Comment by chrispahm** [comment]
https://github.com/chrispahm/chartjs-plugin-dragdata/releases/tag/v1.1.3

**Comment by mortac8** [comment]
That's great.  Thanks!
