### ISSUE TITLE
Compatibility with chart.js 3.0.0

### ISSUE THREAD

**Issue by dbflakes** [chrispahm/chartjs-plugin-dragdata#64]
Is there a new version planned for the latest chart.js?

**Comment by chrispahm** [comment]
Hey 👋 thanks for raising an issue! I haven't got the time to update this yet, but definitely will do once I got some free time. PR are very welcome though 😊

**Comment by chrispahm** [comment]
Alright, just released v2 of this plugin, which is compatible to Chart.js v3 🎉
Beware that the API of the plugin changed (in order to be more consistent with other plugins).
I'll close this issue, please re-open another one if you experience any issues with the new release!
