### ISSUE TITLE
Tooltip values are not being updated when dragging fast

### ISSUE THREAD

**Issue by YahavTheKing123** [chrispahm/chartjs-plugin-dragdata#77]
Hi,

When dragging points fast or in some other times, tooltip is not being updated (in Line chart).
This is happenning also in your examples here:

https://chrispahm.github.io/chartjs-plugin-dragdata/

Can you please suggest?

Thanks in advanced!

**Comment by chrispahm** [comment]
Hey @YahavTheKing123 

not so sure what you mean, this is what's happening when I drag a datapoint (fast) from the given example

![drag_data](https://user-images.githubusercontent.com/20703207/142403083-4300e185-6efa-42e5-88ea-6efc0ef7818c.gif)

The tooltip is always updating, there's a delay in the tooltip position animation that I don't have any control over though.

Is this delay the issue you're describing? Or is something different happening on your end? If so, a video/GIF as well as some more details (e.g. browser used) etc. would be helpful.

Best
Chris

**Comment by YahavTheKing123** [comment]
Thank you for your reply @chrispahm ,

I am not talking about the animation delay. My issue is with the tooltip values that are not being changed (sometimes).
I am adding a video-gif that shows it.

![Animation](https://user-images.githubusercontent.com/38849753/142423652-a7b015da-faed-42c6-b0a6-d5b170778d44.gif)

**Comment by YahavTheKing123** [comment]
Hi,

have you manage to identify this issue?

Thanks :)

**Comment by YahavTheKing123** [comment]
One strage thing here, when the chrome devTools is open, this is not happening... not sure why

**Comment by chrispahm** [comment]
Hey @YahavTheKing123,
While I'm sometimes able to reproduce the issue, I also haven't found out what exactly is causing it... sorry!

**Comment by YahavTheKing123** [comment]
Hi @chrispahm and thank you for your check.
I havent tryed it yet, but do you think that upgrading d3-drag and d3-select to latest version (you are currently work with old version) will make some difference?

Thanks :)

**Comment by chrispahm** [comment]
Hey @YahavTheKing123,
I just released v.2.2.0 with updated dependencies, and also updated examples using Chart.js v3.6.0, but unfortunately still no luck.

It's indeed really strange that the updates seem to work perfectly fine once the developer console is open, which makes it especially hard to debug. In a similar manner, I noticed that the following GANTT-Chart expressed super slow dragging behaviour, which is however fixed as well once the developer console is opened (and the page reloaded with an open dev console)

https://chrispahm.github.io/chartjs-plugin-dragdata/ganttChart.html

Not sure if that's a (temporary) option for you, but the issues doesn't seem to appear using Chart.js v2 (see v2 branch https://github.com/chrispahm/chartjs-plugin-dragdata/tree/v2)

**Comment by chrispahm** [comment]
https://github.com/chartjs/Chart.js/issues/9904

**Comment by YahavTheKing123** [comment]
Thank for that @chrispahm. Unfortunately I need the Chartjs v3...

When thing that i did found is that on FireFox, when devTools is opened, this bug is still reproduceable so maybe it will help when debugging..

Thanks :)

**Comment by chrispahm** [comment]
Thanks to Chart.js maintainer @kurkle we finally have a fix 🎉 (`v2.2.1`) 
You can follow the discussion in chartjs/Chart.js#9904 if you are interested in how the proposed solution works.
https://chrispahm.github.io/chartjs-plugin-dragdata/

Please let me know if the new version also fixes your issue!

**Comment by YahavTheKing123** [comment]
@chrispahm Thank you so much :)
 Having some problems to compile the new version in my environment. Any chance you can create me a version with the old dependencies of your package that contains the new fix?
Thanks alot for everything!

**Comment by chrispahm** [comment]
What's the error you are receiving?

**Comment by YahavTheKing123** [comment]
![image](https://user-images.githubusercontent.com/38849753/144428163-fcee6972-b3a2-4ace-b6d0-c2a83bbb7ad1.png)

This one... not sure why I am getting this but i suspect the new dependcies. This is why I asked to compile it with the older ones...

Thanks in advance @chrispahm  :)

**Comment by chrispahm** [comment]
I see, I checked [caniuse](https://caniuse.com/?search=optional%20chaining) before implementing optional chaining, and figured ~90% availability would be enough. Let me publish a quick fix, it's not used anywhere else so I guess an additional line wouldn't hurt!

Here's a small blogpost on optional chaining, it has a link to the required toolchain: https://chrispahm.github.io/posts/es2020-features.html (for future projects of yours)

**Comment by YahavTheKing123** [comment]
Thank you for the quick response!

1. Thanks for the blogpost, looks good!
2. I am now able to compile my bundle, but for some reason it is still not updating the tooltip new value.

Can you please commit the change here to gihub and also see that the example here work with this version.

Thanks @chrispahm

**Comment by chrispahm** [comment]
Hmm that is strange, did you disable your browsers cache?

**Comment by YahavTheKing123** [comment]
Yep :(
Still not working for me... I will try to share here an example...

**Comment by kurkle** [comment]
@chrispahm I think you should still cancel the replayed (or any) event when dragging. Its going to be the event before drag (because the d3-drag prevents the consumed events, such that chart.js does not receive them), so the event coordinates are at the starting point. This could cause the tooltip (and hover) to change in the `chart.update('none')` call.
I'm not sure that is the cause, but it could be a factor.

**Comment by YahavTheKing123** [comment]
@chrispahm Still working on some example but meanwhile I notice that in your example there is some bug (minor one).
When I drag the point to touch the edges of the chart, then the tooltip value is no longer changes...

**Comment by YahavTheKing123** [comment]
Hi @chrispahm  :),

I created this codeSandbox below. This is more or less my prod setup (except for the zoom plugin which i am using and didnt include here). 

You can see that here with the latest version its also not working well...
https://codesandbox.io/s/damp-resonance-37ixy?file=/src/App.js

Thanks in advance my friend.

**Comment by YahavTheKing123** [comment]
Sorry for bugging you  @chrispahm , but maybe you had a chance to take a look on that?

Thanks :)

**Comment by chrispahm** [comment]
Sorry, I'm really busy with work this week. Will let you know when I get to it!

**Comment by kurkle** [comment]
@chrispahm FYI, you can use https://chartjs.org/dist/master/chart.js (or .min.js etc) in pens etc (not in production!), to test out the master version.

**Comment by chrispahm** [comment]
@kurkle  that's awesome! I didn't know about the `chart.tooltip.update()` method! I guess that one solves both issues at once, will publish a fix ASAP.

@YahavTheKing123 here's the updated CodeSandbox using @kurkle's proposed fix:
https://codesandbox.io/s/musing-margulis-mjkwh?file=/src/chartjs-plugin-dragdata.js

**Comment by chrispahm** [comment]
Published `v2.2.3`, @YahavTheKing123 would appreciate if you could confirm if the fix works for you as well

**Comment by YahavTheKing123** [comment]
@chrispahm you are AMAZING!!!!! Thank you so much for your help (@kurkle to you too!)

I have just tested it with the new version and finally, it works great!!! It was worth waiting :)

Again thanks!

This issue can be closed now :)

**Comment by YahavTheKing123** [comment]
Sorry for all the bugging @chrispahm :(,

Your plugin is working now great. 
I updated my example since its also using the chartjs-plugin-zoom for zoom and pan functionality.

I see some weird behavior after you deployed your new version.
When enabling the pan option in the zoomPlugin, the tooltip is freezing on the previous dragged point even if i am hovering on new point :( (if I disable the pan its working as expected).

I updated the codesandbox https://codesandbox.io/s/ancient-frog-chloh?file=/src/App.j (hope its ok.. I though that when I am editing it, its automatically creates new instance of it..) and you can see the behavior there. 

Can you please suggest how can I address this?

Thanks a lot for your assistance Chris!

**Comment by YahavTheKing123** [comment]
Sorry for all the bugging @chrispahm and @kurkle :(,

Your plugin is working now great.
I updated my example since its also using the chartjs-plugin-zoom for zoom and pan functionality.

I see some weird behavior after you deployed your new version.
When enabling the pan option in the zoomPlugin, the tooltip is freezing on the previous dragged point even if i am hovering on new point :( (if I disable the pan its working as expected).

I updated the codesandbox https://codesandbox.io/s/ancient-frog-chloh?file=/src/App.j (hope its ok.. I though that when I am editing it, its automatically creates new instance of it..) and you can see the behavior there.

Can you please suggest how can I address this?

Thanks a lot for your assistance Chris!

**Comment by kurkle** [comment]
You can use `onPanStart` to reject the pan:
https://codesandbox.io/s/determined-kalam-lvhxf

**Comment by YahavTheKing123** [comment]
@kurkle , it worked like a magic!!!! Thank you!
