### ISSUE TITLE
Line scatter source code not present in README.md

### ISSUE THREAD

**Issue by Francesko90** [chrispahm/chartjs-plugin-dragdata#83]
Hi, Congratulations for the plugin!

Can you put the source code for this example https://chrispahm.github.io/chartjs-plugin-dragdata/scatter.html?
In the  README.md the source code link at the demo

Thanks in advance

**Comment by Francesko90** [comment]
Founded in https://raw.githubusercontent.com/chrispahm/chartjs-plugin-dragdata/master/docs/scatter.html :)

**Comment by chrispahm** [comment]
Hey Francesco, Thanks for the ❤️, and the hint about the wrong link in the readme! Will fix ASAP 😊 Merry Christmas 🎄 

Christoph
