### ISSUE TITLE
not Working X-axis Drag  

### ISSUE THREAD

**Issue by sohaibahsan007** [chrispahm/chartjs-plugin-dragData#9]
please Check Again. Y-Axis is working Fine but X-Axis is not working

**Comment by chrispahm** [comment]
Hey there,
thanks for raising an issue.
Can you elaborate further on the use case which is not working for you?
Note that the X-Axis dragging feature was implemented for charts that feature a linear scale on the X-Axis, e.g. scatter charts and bubble charts . In case you have a chart with a non-linear x-axis (e.g. a line chart with a category axis as 'January', 'Febuary', etc.), dragging the X-Axis does not really make sense. At least I don't know what one would expect to happen if you drag along the X-Axis.
Here is a fiddle with a scatter chart with a draggable y and x-axis.
[Scatter chart example](https://www.chartjs.org/docs/latest/charts/scatter.html).
[Bubble chart example](https://chrispahm.github.io/chartjs-plugin-dragData/bubble.html)

**Comment by chrispahm** [comment]
Closing this as answered.
