### ISSUE TITLE
How to eliminate the single point of drag and drop, by the user complete control of drag-and-drop behavior

### ISSUE THREAD

**Issue by zhelizhu** [chrispahm/chartjs-plugin-dragdata#94]
**Describe the bug**

**To Reproduce**
Please use any of the available templates on either
[jsFiddle](https://jsfiddle.net/etnLwxfa/1/),
[plunker](https://plnkr.co/edit/aJFm7Gb5uRqoekmd?open=lib%2Fscript.js),
or [codepen](https://codepen.io/chrispahm/pen/RwGBrEr) to give a reproducible example showcasing the issue.

**Expected behavior**

**Comment by chrispahm** [comment]
Hey @zhelizhu,

Sorry, but could you elaborate a little more on what you are trying to achieve?
Furthermore, as it seems this is rather asking for advice than describing a bug, I'd like to redirect you to the [Discussions](https://github.com/chrispahm/chartjs-plugin-dragdata/discussions) section.
